//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchetsredstv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Средство
    {
        public int ИД_Средства { get; set; }
        public int Инвентарный_номер { get; set; }
        public string Модель { get; set; }
        public System.DateTime Дата_приобретения { get; set; }
        public int Стоимость { get; set; }


    }
}
